apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "configuration/*").AsConfig | nindent 2 }}