apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: home-assistant
          image: {{ include "home-assistant.image" . }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
              