apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: create-users
          image: {{ include "home-assistant.image" . }}
          command:
          - sh
          - -c
          - |
            set -eu
            addgroup "$NAME" -g "$ID"
            adduser "$NAME" -u "$ID" -G "$NAME" -D -H
            cp -rf /etc/passwd /etc/group $DIRECTORIES /init-tmp/
            chown -R "$NAME:$NAME" /init-tmp

            apk add envsubst
            envsubst < /config/secrets.yaml > /init-tmp/secrets.yaml
          env:
            - name: NAME
              value: home-assistant
            - name: ID
              value: "1000"
            - name: DIRECTORIES
              value: /config
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: home-assistant.home-assistant-postgresql.credentials.postgresql.acid.zalan.do
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: home-assistant.home-assistant-postgresql.credentials.postgresql.acid.zalan.do
                  key: username
          volumeMounts:
            - name: init-tmp
              mountPath: /init-tmp
            - name: secrets
              mountPath: /config/secrets.yaml
              subPath: secrets.yaml
      containers:
        - name: home-assistant
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: {{ include "home-assistant.image" . }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: init-tmp
              mountPath: /etc/passwd
              subPath: passwd
            - name: init-tmp
              mountPath: /etc/group
              subPath: group
            - name: init-tmp
              mountPath: /config
              subPath: config
            - name: init-tmp
              mountPath: /config/secrets.yaml
              subPath: secrets.yaml
            - name: secrets
              mountPath: /config/serviceAccount.json
              subPath: serviceAccount.json
            {{- range $path, $_ := .Files.Glob "configuration/*" }}
            - name: configs
              mountPath: /config/{{ $path | base }}
              subPath: {{ $path | base }}
            {{- end }}
      volumes:
        - name: init-tmp
          emptyDir: {}
        - name: secrets
          secret:
            secretName: {{ .Chart.Name }}
        - name: configs
          configMap:
            name: {{ .Chart.Name }}
